# Generated by Django 5.1.1 on 2024-12-13 05:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='farmers_photos/')),
                ('rsbsa_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('ext_name', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('pwd', models.BooleanField(default=False)),
                ('fourps_beneficiary', models.BooleanField(default=False)),
                ('contact_no', models.CharField(max_length=11, null=True)),
                ('religion', models.CharField(default='', max_length=10)),
                ('educ_attainment', models.CharField(choices=[('Pre-school', 'Pre-school'), ('Elementary', 'Elementary'), ('High School (non K-12)', 'High School (non K-12)'), ('Junior High School (K-12)', 'Junior High School (K-12)'), ('Senior High School (K-12)', 'Senior High School (K-12)'), ('College', 'College'), ('Post Graduate', 'Post Graduate'), ('Vocational', 'Vocational'), ('None', 'None')], default='High School', max_length=50)),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widow/er', 'Widow/er'), ('Legally Separated', 'Legally Separated')], default='Single', max_length=50)),
                ('date_of_birth', models.DateField(null=True)),
                ('birthplace', models.CharField(default='', max_length=100)),
                ('indigenous_people', models.BooleanField(default=False, null=True)),
                ('indeigenous_specify', models.CharField(default='', max_length=100, null=True)),
                ('house_no', models.CharField(default='', max_length=10)),
                ('street', models.CharField(default='', max_length=100)),
                ('municipality', models.CharField(default='Matnog', max_length=100)),
                ('province', models.CharField(default='Sorsogon', max_length=100)),
                ('region', models.CharField(default='V - Bicol', max_length=100)),
                ('name_of_spouse', models.CharField(blank=True, max_length=100)),
                ('mothers_maiden', models.CharField(max_length=100)),
                ('name_of_household_head', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('household_members', models.IntegerField()),
                ('household_male', models.IntegerField()),
                ('household_female', models.IntegerField()),
                ('govern_id', models.BooleanField(default=False)),
                ('id_type', models.CharField(blank=True, max_length=50, null=True)),
                ('id_no', models.CharField(blank=True, max_length=100, null=True)),
                ('if_emergency', models.CharField(max_length=100)),
                ('emergency_contact', models.CharField(max_length=11)),
                ('member_of_farmers_associate', models.BooleanField(default=False)),
                ('specify', models.CharField(blank=True, max_length=100, null=True)),
                ('main_livelihood', models.CharField(choices=[('Farmer', 'Farmer'), ('Farmworkers', 'Farmworkers'), ('Fisherfolk', 'Fisherfolk')], default='Farmer', max_length=20)),
                ('specify_position', models.CharField(blank=True, max_length=100, null=True)),
                ('north_neighbor', models.CharField(blank=True, max_length=100)),
                ('south_neighbor', models.CharField(blank=True, max_length=100)),
                ('east_neighbor', models.CharField(blank=True, max_length=100)),
                ('west_neighbor', models.CharField(blank=True, max_length=100)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.barangay')),
                ('commodities', models.ManyToManyField(to='farmers.commodity')),
            ],
        ),
    ]
